on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.13.1/trunktr-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - run: trunk build
      - name: deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
